# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: "python:3.7" 
#commands to run in the Docker container before starting each job.
before_script:
  - python --version
  - pip install -r requirements.txt
# different stages in the pipeline
stages:
  - Static Analysis
  - Test
  - Deploy
# Static Analysis
pylint:
  stage: Static Analysis
  script:
  - pylint -d C0301 src/*.py
# Test
pytest:
  stage: Test
  script:
  - cd test/;pytest -v
# Deploy
MSDeploy:
  stage: Deploy
  script:
  - echo "test ms deploy"
  - cd src/
  - pyinstaller -F lintpractice.py
  tags:
  - DeployMS
  artifacts:
    paths:
      - src/dist/*.exe