# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: "python:3.7" 
#commands to run in the Docker container before starting each job.
before_script:
  - python --version
  - python -m pip install -r requirements.txt
# different stages in the pipeline
stages:
  - Test
  - Deploy
# Test
pytest:
  stage: Test
  script:
  - pytest -v
# Deploy
MSDeploy:
  stage: Deploy
  script:
  - echo "test ms deploy"
  - cd src/
  - pyinstaller -F *.py
  artifacts:
    paths:
      - src/dist/*.exe
      - src/screens
      - ../img/*.png
