# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
import loginQueries as lq
import registerUI as rUI
import mainmenu
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.uic import loadUi

class Login(QtWidgets.QDialog):
    def __init__(self):
        super(Login, self).__init__()
        loadUi('login.ui', self)
        self.setWindowTitle("Login Form")
        self.btn_login.clicked.connect(self.login_clicked)
        self.btn_register.clicked.connect(self.register_clicked)
        self.btn_register.clicked.connect(self.close)

    def clear(self):
        self.line_email.clear()
        self.line_password.clear()

    def login_clicked(self):
        email = self.line_email.text()
        password = self.line_password.text()
        if email == "" or password == "":
            self.lbl_notification.setText("Tolong isi email dan password dengan benar")
            return
        if not lq.isEmailExist(email):
            self.lbl_notification.setText("Email belum terdaftar, silahkan register")
            self.clear()
            return
        loginInfo = lq.getLoginInfo(email)
        databasePass = loginInfo[0]
        databaseRole = loginInfo[1]
        if password != databasePass:
            self.lbl_notification.setText("Password salah")
            self.clear()
            return
        self.clear()
        self.close()
        main_page = mainmenu.MainMenu(email)
        main_page.exec_()
        # Jika password benar, maka akan ke Main Menu
        return

    def register_clicked(self):
        self.close()
        register_page = rUI.Register()
        register_page.exec_()
        return

def startLoginDialog():
    app = QtWidgets.QApplication(sys.argv)
    widget = Login()
    widget.show()
    sys.exit(app.exec_())
    return

if __name__ == "__main__":
    startLoginDialog()
