# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
import loginQueries as lq
import loginUI as lUI
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.uic import loadUi

class Register(QtWidgets.QDialog):
    def __init__(self):
        super(Register, self).__init__()
        loadUi('register.ui', self)
        self.setWindowTitle("Register Form")
        self.btn_login.clicked.connect(self.login_clicked)
        self.btn_register.clicked.connect(self.register_clicked)

    def login_clicked(self):
        self.close()
        login_page = lUI.Login()
        login_page.exec_()
        return
    
    def register_clicked(self):
        nama = self.line_nama.text()
        email = self.line_email.text()
        password = self.line_password.text()
        upin = self.line_pin.text()
        number = self.line_number.text()
        if nama == "" or email == "" or password == "" or upin == "" or number == "":
            self.lbl_notification.setText("Tolong untuk mengisi seluruh bagian dengan benar")
            return
        if len(upin) != 6 or upin.isdecimal() == False:
            self.lbl_notification.setText("PIN harus merupakan angka berjumlah 6")
            return
        if number.isdecimal() == False:
            self.lbl_notification.setText("Nomor telepon harus merupakan angka")
            return
        lq.addCustomerEntry(nama, email, password, number, upin)
        self.close()
        login_page = lUI.Login()
        login_page.exec_()
        return

def startRegisterDialog():
    app = QtWidgets.QApplication(sys.argv)
    widget = Register()
    widget.show()
    sys.exit(app.exec_())
    return

if __name__ == "__main__":
    startRegisterDialog()
