# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
import loginQueries as lq
import loginUI as lUI
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.uic import loadUi

def login_clicked(dialog):
    dialog.close()
    login_page = lUI.LoginProcedural()
    login_page.exec_()
    return

def register_clicked(dialog):
    nama = dialog.line_nama.text()
    email = dialog.line_email.text()
    password = dialog.line_password.text()
    upin = dialog.line_pin.text()
    number = dialog.line_number.text()
    if nama == "" or email == "" or password == "" or upin == "" or number == "":
        dialog.lbl_notification.setText("Tolong untuk mengisi seluruh bagian dengan benar")
        return
    if len(upin) != 6 or upin.isdecimal() == False:
        dialog.lbl_notification.setText("PIN harus merupakan angka berjumlah 6")
        return
    if number.isdecimal() == False:
        dialog.lbl_notification.setText("Nomor telepon harus merupakan angka")
        return
    lq.addCustomerEntry(nama, email, password, number, upin)
    dialog.close()
    login_page = lUI.LoginProcedural()
    login_page.exec_()
    return

def RegisterProcedural():
    dialog = QtWidgets.QDialog()
    loadUi('register.ui', dialog)
    dialog.setWindowTitle("Register Form")
    dialog.btn_login.clicked.connect(lambda: login_clicked(dialog))
    dialog.btn_register.clicked.connect(lambda: register_clicked(dialog))
    return dialog

def startRegisterProcedural():
    app = QtWidgets.QApplication(sys.argv)
    dialog = RegisterProcedural()
    dialog.show()
    sys.exit(app.exec_())
    return

if __name__ == "__main__":
    startRegisterProcedural()
